const berriesData = [
    {
        id: 1,
        name: 'Виноград зелений',
        category: "berry",
        minOrder: '0.5 кг',
        available: false,
    },
    {
        id: 2,
        name: 'Виноград Киш Миш',
        category: "berry",
        minOrder: '0.5 кг',
        available: true,
    },
    {
        id: 3,
        name: 'Виноград синій',
        category: "berry",
        minOrder: '0.5 кг',
        available: true,
    },
    {
        id: 4,
        name: 'Диня DINO',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 5,
        name: 'Диня Пієль де Сапо',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 6,
        name: 'Журавлина свіжа',
        category: "berry",
        minOrder: '0.5 кг',
        available: true,
    },
    {
        id: 7,
        name: 'Кавун',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 8,
        name: 'Лохина 125г (уп.)',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 9,
        name: 'Малина 150г (уп.)',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 10,
        name: 'Ожина 150г (уп.)',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 11,
        name: 'Полуниця',
        category: "berry",
        minOrder: '0.5 кг',
        available: false,
    },
    {
        id: 12,
        name: 'Фізаліс 100г (уп.)',
        category: "berry",
        minOrder: '1 шт',
        available: false,
    },
    
];