const exoticsData = [
    {
        id: 1,
        name: 'Гранаділа',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 2,
        name: 'Карамболь',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 3,
        name: 'Ківано',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 4,
        name: 'Ківі голд Преміум',
        category: "exotic",
        minOrder: '5 шт',
        available: false,
    },
    {
        id: 5,
        name: 'Кокос',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 6,
        name: 'Кокос молодий питний',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 7,
        name: 'Кумкват',
        category: "exotic",
        minOrder: '10 шт',
        available: false,
    },
    {
        id: 8,
        name: 'Лічі',
        category: "exotic",
        minOrder: '10 шт',
        available: false,
    },
    {
        id: 9,
        name: 'Манго EAT ME',
        category: "exotic",
        minOrder: '1 шт',
        available: true,
    },
    {
        id: 10,
        name: 'Манго Королівське',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 11,
        name: 'Мангостін',
        category: "exotic",
        minOrder: '5 шт',
        available: false,
    },
    {
        id: 12,
        name: 'Маракуйя фіолетова (Пешн фрут)',
        category: "exotic",
        minOrder: '5 шт',
        available: false,
    },
    {
        id: 13,
        name: 'Папая',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 14,
        name: 'Папая королівська',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 15,
        name: 'Пітахайя жовта',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 16,
        name: "Пітахайя червона з білою м'якоттю",
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 17,
        name: "Пітахайя червона з червоною м'якоттю",
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    },
    {
        id: 18,
        name: 'Рамбутан',
        category: "exotic",
        minOrder: '5 шт',
        available: false,
    },
    {
        id: 19,
        name: 'Тамаринд 450г (уп.)',
        category: "exotic",
        minOrder: '1 шт',
        available: false,
    }
];