const spicesData = [
    {
        id: 1,
        name: 'Аджика суха',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '11',
    },
    {
        id: 2,
        name: 'Аніс цілий',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '20',
    },
    {
        id: 3,
        name: 'Бодян цілий',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '50',
    },
    {
        id: 4,
        name: 'Барбарис',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '35',
    },
    {
        id: 5,
        name: 'Гвоздика ціла',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '50',
    },
    {
        id: 6,
        name: 'Гірчиця мелена',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '9',
    },
    {
        id: 7,
        name: 'Гірчиця ціла',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '9',
    },
    {
        id: 8,
        name: 'Зіра мелена',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '21',
    },
    {
        id: 9,
        name: 'Зіра ціла',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '25',
    },
    {
        id: 11,
        name: 'Кориця паличка (шт)',
        category: "spices",
        minOrder: '5 шт',
        available: false,
        price: '25',
    },
    {
        id: 12,
        name: 'Кориця мелена',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '14',
    },
    {
        id: 13,
        name: 'Мускатний горіх цілий (шт)',
        category: "spices",
        minOrder: '5 шт',
        available: false,
        price: '40',
    },
    {
        id: 14,
        name: 'Мускатний горіх мелений',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '25',
    },
    {
        id: 15,
        name: 'Ваніль паличка (шт)',
        category: "spices",
        minOrder: '1 шт',
        available: false,
        price: '105',
    },
    {
        id: 16,
        name: 'Папріка копчена мелена',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '15',
    },
    {
        id: 17,
        name: 'Перець солодкий сушенений мелений',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '13',
    },
    {
        id: 18,
        name: 'Перець чілі сушений різаний',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '17',
    },
    {
        id: 19,
        name: 'Сванська сіль',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '13',
    },
    {
        id: 20,
        name: 'Сумах',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '20',
    },
    {
        id: 21,
        name: "Суміш для м'яса",
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 22,
        name: 'Суміш для перших страв',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '25',
    },
    {
        id: 23,
        name: 'Суміш для плову',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 24,
        name: 'Суміш для риби',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 25,
        name: 'Уцхо сунелі',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '17',
    },
    {
        id: 26,
        name: 'Хмелі сунелі',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '9',
    },
    {
        id: 27,
        name: 'Куркума',
        category: "spices",
        minOrder: '50 г',
        available: false,
        price: '9',
    },
    {
        id: 28,
        name: 'Набір для глінтвейну',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '50',
    },
    {
        id: 29,
        name: 'До картоплі',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 30,
        name: 'Для моркви по корейськи',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 31,
        name: 'Універсальна',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 32,
        name: '10 овочів',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
    {
        id: 33,
        name: 'До курки',
        category: "spices",
        minOrder: '50 г',
        available: true,
        price: '25',
    },
];